### ISSUE TITLE
Undefined property: stdClass::$name

### ISSUE THREAD

**Issue by albertojm** [auth0/laravel-auth0-sample#10]
The object Auth0::jwtuser() returns:

`object(stdClass)#185 (5) {
  ["iss"]=>
  string(26) "https://rasbora.auth0.com/"
  ["sub"]=>
  string(30) "auth0|11ab26e662c35d513019fd8"
  ["aud"]=>
  string(32) "6rQBdJFe3Uh7s0GYKNSWyX8KifO8uKsq"
  ["exp"]=>
  int(1461403416)
  ["iat"]=>
  int(1461367416)
}`

Therefore the property name as indicated on this sample does not exists:

`Undefined property: stdClass::$name`

How can I get this property (along with email, registration date, etc) in order to save the user to my local database?

Thanks.

**Comment by glena** [comment]
you must be missing the `name` scope when you authenticated the user. Check https://auth0.com/docs/scopes

**Comment by several27** [comment]
I'm getting the same error. AngularJS sees the email properly, but when I pass the token to laravel, I get the same properties as @albertojm.
@glena How should we add the name scope?

**Comment by glena** [comment]
@several27 check this example https://github.com/auth0/auth0-angular#displaying-the-signin-popup-and-retrieving-user-information

there is a property sent to the signin method ```authParams: {
        scope: 'openid name email' // Specify the scopes you want to retrieve
      }```

**Comment by several27** [comment]
Thank you!

**Comment by cwhittl** [comment]
HI @glena I'm getting the same error as @albertojm when following https://auth0.com/docs/quickstart/backend/php-laravel.  I understand what you are saying but not sure how to implement the scope in this context..  Can you provide more info?

Thanks!

**Comment by glena** [comment]
When you ask for a token, there is a param called `scope`. If you use the hosted login page it is the `scope` query param in the `/authorize?client_id=...&redirect_uri=...&response_type=...&scope=...` url. if you use lock 10, you need to set it in the options:

```
var auth0 = new Auth0Lock(CLIENT_ID, DOMAIN, {
  auth: {
    params: {
      scope: ''
    }
  }
});```
