### ISSUE TITLE
Heroku PHP buildpack

### ISSUE THREAD

**Issue by fadlisaad** [auth0/laravel-auth0-sample#13]
While executing this line:
`heroku create --buildpack https://github.com/heroku/heroku-buildpack-php\#beta`
you'll find error:
`ERROR: The 'beta' branch of this buildpack is no longer supported. Please switch to the release version by removing BUILDPACK_URL from your configuration using 'heroku config:unset BUILDPACK_URL'. See http://devcenter.heroku.com/categories/php for more information.`
Trying to to use:
`heroku config:unset BUILDPACK_URL`, you'll get the same error. 
After looking at heroku PHP buildpack repository, the suggestted command is:
`heroku buildpacks:set heroku/php`
Then just follow the rest of the instruction: 
`git push heroku master`

**Comment by glena** [comment]
Like this https://github.com/auth0/laravel-auth0-sample/commit/12942b1b86a4ef36d0321273621b7c75f4b039d1, right?

Thx for the heads up :)
