### ISSUE TITLE
Auth0::jwtuser()->name NOT WORKING

### ISSUE THREAD

**Issue by ratatatKE** [auth0/laravel-auth0-sample#2]
Hi guys, I am trying to access the name of the logged in user in auth0 through laravel but this is not working. I try
 Auth0::jwtuser()->name
As declared on the Angular and laravel tutorial but this gives me call to an undefined object. 
I am not sure what I am doing wrong.
My front end is in angular js which sends a jwt token to the server for which the laravel filter works perfectly fine, and so i know that actually auth0 works upto this extent, but then calling 
 Auth0::jwtuser()->name just does not work. 
Furthermore, the Auth0::onLogin does not also fire up

here is my routes.php
         <?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function () {
    return View::make('hello');
});
//Just a demo
Route::get('/api/protected', array('before' => 'auth-jwt', function () {
    return "Hello " . Auth0::jwtuser()->name;
}));
// The auth jwt filters against just plain old non logged in users whereas the admin and officer filters are role specific and they are declared in the specific controllers sir
Route::group(['prefix' => 'api_v1', 'before' => 'auth-jwt'], function () {
//    Then here we will have all of our resourceful controllers which will sort of manage the backend for us
    Route::resource('publicofficer', 'PublicOfficerController');
    Route::resource('governmentofficer', 'GovernmentOfficerController');
    Route::resource('child', 'ChildController');
    Route::resource('childprofileimages', 'PhotosController');
    Route::resource('govtofficerroles', 'GovtOfficerRoleController');
    Route::resource('publicofficerroles', 'PublicOfficerRoleController');

});

// This is the hook from the plugin that lets us know that a user has logged in
// and we should either return the real db user or create a new one
// This should be somewhere else.
Auth0::onLogin(function ($auth0User) {
    // See if the user exists
    $user = User::where("email", $auth0User->email)->first();
    echo "This is the user " . $user;
    if ($user === null) {
        // If not, create one
        $user = new User();
        $user->email = $auth0User->email;
        $user->password = Hash::make('admin');
        $user->save();
    }
    return $user;
});

And this is a portion of my angular js jwt interceptor
![screenshot 53](https://cloud.githubusercontent.com/assets/8273966/5997874/eb812718-aad1-11e4-958c-083f82e2a1ad.png)

**Comment by danielpaul** [comment]
@ratatatKE Did you find a solution to this? I'm facing the same issue...

**Comment by webface** [comment]
Im facing the same issue. Looking for a solution

**Comment by glena** [comment]
@webface are you asking for the proper scopes?

**Comment by webface** [comment]
I have asked for the proper scopes now it is working

Regards,
*Tommy Adeniyi*
*647.966.8624*
tommyadeniyi@gmail.com
www.webfacemedia.com

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee, you should not
disseminate, distribute or copy this email. Please notify the sender
immediately by email if you have received this email by mistake and delete
this email from your system. Email transmission cannot be guaranteed to be
secure or error-free, as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender,
therefore, does not accept liability for any errors or omissions in the
contents of this message which arise as a result of email transmission. If
verification is required, please request a hard-copy version.
